default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_40934_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_40934_test



production:
  <<: *default
  database: protospace_40934_production
  username: protospace_40934
  password: <%= ENV["PROTOSPACE_40934_DATABASE_PASSWORD"] %>
